
services:
  louka-loca-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: louka-loca-api:1.0.0
    container_name: louka-loca-api
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.louka-loca-api.rule=Host(`${DOMAINE_NAME}`)
    #   - traefik.http.routers.louka-loca-api.entrypoints=web
    #   - traefik.http.routers.louka-loca-api-secure.rule=Host(`${DOMAINE_NAME}`)
    #   - traefik.http.routers.louka-loca-api-secure.entrypoints=websecure
    #   - traefik.http.routers.louka-loca-api-secure.tls.certresolver=letsencrypt
    #   - traefik.http.services.louka-loca-api.loadbalancer.server.port=80
    networks:
      - traefik_network
    command: >
      sh -c "
      php artisan migrate --force &&
      php artisan db:seed --force &&
      php-fpm
      "

  louka-loca-nginx:
    image: nginx:alpine
    container_name: louka-loca-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - louka-loca-api
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
