server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass louka-loca-api:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param APP_ENV production;
    }

    location ~ /\.ht {
        deny all;
    }

    error_log  /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
}
