name: Deploy Laravel API

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22  # Modifiez ce numéro de port si nécessaire
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          connect_timeout: 30s
          first_ssh: |
            echo "Preparing deployment on server"
            cd ${{ secrets.DEPLOY_PATH }}
            rm -rf ./*
          scp: |
            ./* ${{ secrets.DEPLOY_PATH }}
          last_ssh: |
            cd ${{ secrets.DEPLOY_PATH }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

      - name: Clean up local resources
        run: |
          echo "Clean up completed"
